- name: Run GitLab Image
  docker_container:
    name: GitLab
    image: gitlab/gitlab-ce
    tty: true
    detach: yes
    volumes:
    - "{{ GitLab_host_vol }}:{{ GitLab_contianer_vol }}" 
    state: started
    ports: 
    - "8080:8080"